### PR TITLE
fix: CI error of codeql anaylzer

### LINKED ISSUE #48: Fix CI error of codeql anaylzer
See: https://github.com/casbin-net/casbin-aspnetcore/runs/7634763707?check_suite_focus=true

image

### PR DESCRIPTION
**Pull request by AsakusaRinne**
Add a new sdk version in ci to fix #48

### CODE REVIEW

**Comment by hsluoyz** [comment]
@sagilio

**Review by sagilio — CHANGES_REQUESTED** [review]
@AsakusaRinne plz use multiple versions instead of this:
https://github.com/casbin-net/casbin-aspnetcore/blob/26c4745408c04c12fa5adda52deca349c6d223af/.github/workflows/build.yml#L25-L33

**Comment by hsluoyz** [comment]
@AsakusaRinne fix warnings:

image

**Comment by hsluoyz** [comment]
@AsakusaRinne have the warnings been fixed?

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne have the warnings been fixed?

Yes, the warning mentioned above has been solved by forced push.

**Pull request merged**
