### PR TITLE
feat: Sync authorization data with Casbin2.x generics.

### PR DESCRIPTION
**Pull request by AsakusaRinne**
1. Limit the output of Transformer to ```string[]```.
2. Add adapter for customized authorization data to process customized data type.
3. Use generics API of enforcer of Casbin 2.x when no customized data is applied.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@AsakusaRinne plz review

**Comment by hsluoyz** [comment]
@AsakusaRinne fix:

image

**Comment by AsakusaRinne** [comment]
> @AsakusaRinne fix:
> 
> image

The preview version still uses the "msater" version dependency of Casbin.NET, which made the CI fail. I have updated the PR just now for a major revision. However, the CI will still fail due to the same reason. Please just ignore it and I'll keep sync with Sagilio about this PR.

**Comment by AsakusaRinne** [comment]
@sagilio Please help to have a review when you're free. I have made the major revision mentioned in the meeting last night. Thank you.

**Review by sagilio — COMMENTED** [review]
This implementation is still quite different from what we discussed, here are several important points:
1. At least the path to pass TRequest not be packed to IRequestValues.
2. Can not reduce the information of ICasbinAuthorizationData

As a result, this may make the most APIs cover generics. To descript my thoughts more clear, I will provide a baseline implementation later.

**Comment by sagilio** [comment]
> > @AsakusaRinne fix:
> > image
> 
> The preview version still uses the "msater" version dependency of Casbin.NET, which made the CI fail. I have updated the PR just now for a major revision. However, the CI will still fail due to the same reason. Please just ignore it and I'll keep sync with Sagilio about this PR.

We update the build version of Casbin here: https://www.myget.org/feed/casbin-net/package/nuget/Casbin.NET

**Comment by sagilio** [comment]
> This implementation is still quite different from what we discussed, here are several important points:
> 
> 1. At least the path to pass TRequest not be packed to IRequestValues.
> 2. Can not reduce the information of ICasbinAuthorizationData
> 
> As a result, this may make the most APIs cover generics. To descript my thoughts more clear, I will provide a baseline implementation later.

@AsakusaRinne Here is the another implementation: https://github.com/casbin-net/casbin-aspnetcore/pull/46

**Pull request closed without merging**
